### ISSUE TITLE
Add an argument to edit colors of the heatmap

### ISSUE THREAD

**Issue by Xuemin-Wang** [caijun/ggcorrplot2#4]
Dear Caijun,

Currently ggcorrplot2 uses red for low correlation coefficients and blue for high values. Will you be able to add an argument to ggcorrplot to change the colors? Maybe something similar to corrplot: 
col <- colorRampPalette(c('blue', 'white', 'red'))(20)
ggcorrplot(rg_mat,  method="square", col=col, ...)

Many thanks,
xuemin

**Comment by mathesong** [comment]
Dear @caijun ,

I've just made a PR with this feature.

Many thanks for the package!
/Granville

**Comment by caijun** [comment]
@mathesong Thanks for your fix. I will close this issue via your PR https://github.com/caijun/ggcorrplot2/pull/5
